(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??'');
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=$(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth',block:'start'})}}));
window.DemoUI={
 openProduct({title,category,description,image,ctaHref='#booking',cta='Saznajte više'}){let d=$('#productModal');if(!d){d=document.createElement('dialog');d.id='productModal';d.className='modal';document.body.append(d)}d.innerHTML=`<button class="modal-close" type="button" aria-label="Zatvori">×</button><div class="product-modal"><div class="modal-media"><img src="${image}" alt="${esc(title)}"></div><div class="modal-copy"><span class="kicker">${esc(category||'IZDVAJAMO')}</span><h2>${esc(title)}</h2><p>${esc(description||'')}</p><a class="btn" href="${ctaHref}" data-modal-cta>${esc(cta)}</a></div></div>`;$('.modal-close',d).onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()};$('[data-modal-cta]',d).onclick=()=>d.close();if(!d.open)d.showModal()},
 openRequest(message){let d=$('#requestModal');if(!d){d=document.createElement('dialog');d.id='requestModal';d.className='modal';document.body.append(d)}const enc=encodeURIComponent(message);d.innerHTML=`<button class="modal-close" type="button" aria-label="Zatvori">×</button><div class="request-modal"><span class="kicker">PORUKA JE SPREMNA</span><h2>Pošaljite zahtev</h2><div class="message-box"></div><div class="message-actions"><a class="btn" target="_blank" rel="noopener" href="https://wa.me/?text=${enc}">WhatsApp</a><a class="btn secondary" href="viber://forward?text=${enc}">Viber</a><button class="btn secondary copy" type="button">Kopirajte poruku</button></div></div>`;$('.message-box',d).textContent=message;$('.modal-close',d).onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close()};$('.copy',d).onclick=()=>{navigator.clipboard?.writeText(message);$('.copy',d).textContent='Kopirano'};if(!d.open)d.showModal()},
 bindRequest(form,build){form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;window.DemoUI.openRequest(build(new FormData(form)))})},
 bindChips({root=document,chipSelector,itemSelector,attr='category'}){const chips=$$(chipSelector,root),items=$$(itemSelector,root);chips.forEach(chip=>chip.addEventListener('click',()=>{chips.forEach(x=>x.classList.toggle('active',x===chip));const value=chip.dataset.filter||'Sve';items.forEach(item=>item.hidden=value!=='Sve'&&item.dataset[attr]!==value)}))}
};})();
